### ISSUE TITLE
Unable to Run on Windows 

### ISSUE THREAD

**Issue by ahoadshieldpay** [cypress-io/cypress-realworld-app#420]
1. Cloned the repository
2. ran yarn install
3. On running yarn start i got the below error:
`$ cp data/database-seed.json data/database.json
'cp' is not recognized as an internal or external command,
operable program or batch file.`

4. Changed the cp commands to copy so they would work on windows. 
5. Then got the below error:
`$ copy data/database-seed.json data/database.json
data\database-seed.json
The file cannot be copied onto itself.
        0 file(s) copied.`

5. Changed the / in package.json to \\
6. Then got the below error:
`NODE_ENV=development concurrently yarn:start:react yarn:start:api
'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.`

7. Added SET before NODE_ENV
8. No errors on running yarn start this time but also appears that nothing has started
9. Run yarn cypress:open and try running a test
10. Get errors due to app not starting

**Comment by kevinold** [comment]
Hi @ahoadshieldpay,

Thanks for this report.  

Which version of Windows are you running?
What terminal program are you using?

**Comment by ahoadshieldpay** [comment]
Version: Windows 10 pro
Terminal: The terminal in Visual Studio Code

**Comment by anubhavsinghal07** [comment]
@kevinold.

Getting exactly same issue in Win 7, using cmd terminal.

**Comment by LucasL94** [comment]
Hello and sorry to intrude in this post. Just want to say that I was having the same issue on Windows 10. However, I cloned the `fix-windows` branch and everything's up and running perfectly now.

Thanks @kevinold. That was a quick response 👍

**Comment by frogcatcher** [comment]
Hi @LucasL94. I'm completely new to this.  Would you mind providing additional details about your fix?  Where is the fix-windows branch?

**Comment by amirrustam** [comment]
@frogcatcher the draft PR is displayed within this thread above, here is the PR link for your convenience: https://github.com/cypress-io/cypress-realworld-app/pull/421

**Comment by frogcatcher** [comment]
Hi Amir,

Thank you for your response.  I'm not that technical.  For some reason,
Selenium was easy to install and run, simply following step by step
instructions. I was able to put in some python code and observe the
automated tests run.

However, I heard that Cypress with the up and coming contender to Selenium,
so I wanted to give it a try.  However, I'm and have been struggling with
Cypress, although the instructions for getting Cypress up and running
appear simpler than the procedures that I followed for getting Selenium
installed and running.

And like the others who wrote into the issues threads, I get the exact same
error messages.  I  can't get this working on either my windows 10 or an
Ubuntu vm. I am experiencing the exact same issues as the issues that have
been closed/resolved already.

With regards to 421, here is a screen capture. I am thinking that I need to
merge/pull these changes, but I don't have that authority/option?

[image: image.png]
Thanks again for your help and time.
Melinda

**Comment by ahoadshieldpay** [comment]
> Hello and sorry to intrude in this post. Just want to say that I was having the same issue on Windows 10. However, I cloned the `fix-windows` branch and everything's up and running perfectly now.
> 
> Thanks @kevinold. That was a quick response 👍

I've also just tried cloning the pull request and things are getting further, but on running yarn start or yarn dev I am now getting a compile error:

`Error: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'`

**Comment by LucasL94** [comment]
@frogcatcher the pull request is code that has been sent to a specific branch, that's where it's tested and prepare before merging to the main one. The branch it was sent to is that one that I mentioned before. You can look for the different branches while being on the `code` tab

@ahoadshieldpay that might be happening because if you check the pull request, there are new dependencies added in the package.json.
Try running `yarn install` again and it should be fixed

**Comment by amirrustam** [comment]
@LucasL94 we appreciate your efforts in helping out the community. 🙏

**Comment by ahoadshieldpay** [comment]
@LucasL94 still no luck, but thanks for the help.

I tried again from the beginning - deleted it all and cloned again, cloned the pull request and ran through the steps again including yarn install.

Still getting compile error:
`Error: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'`

**Comment by kevinold** [comment]
Hi @ahoadshieldpay,

What version of Node are you running?  In the VS Code Terminal type `node --version` and please report back.

These updates are set to work against Node version 12.x

**Comment by ahoadshieldpay** [comment]
v14.3.0

**Comment by kevinold** [comment]
> v14.3.0

@ahoadshieldpay 

Yes, that is the issue you are seeing now.  We are using Node version 12, so you will need to downgrade in order to use this application.

**Comment by ahoadshieldpay** [comment]
> > v14.3.0
> 
> @ahoadshieldpay
> 
> Yes, that is the issue you are seeing now. We are using Node version 12, so you will need to downgrade in order to use this application.

I have downgraded, now on v12.18.0

Went through all the steps again but still getting the same error.

**Comment by frogcatcher** [comment]
I gave up and removed everything and did a new git.  And got the same errors.
Then, I _finally_ found the fix-windows Branch here: https://github.com/cypress-io/cypress-realworld-app/tree/fix-windows    * But, I do not know what action to take/what commands to run to get this fix-window branch incorporated. 
Note:  I *thought* starting over (see first statement) would be the novice solution to get whatever was in fix-windows, but I didn't experience any progress in my re-do attempt. 
Could someone please explain to me what steps I need to take to get those fix-windows branch changes?

Also, been following the threads.  
I'm using Windows 10, Node version 12.x, and did according to ahoadshieldpay and added SET in front of NODE_ENV.

I continue to get stuck on this error when I enter the command yarn start or yarn dev.  
----------------------
$ yarn db:seed:dev
$ copy data/database-seed.json data/database.json
data\database-seed.json
The file cannot be copied onto itself.
-----------------------------
ahoadshieldpay mentioned fixing the \ to /.  However, I do not see the \ in the package.json file.  All of them are \.   Is there somewhere else that I need to make this change?

Thank you!

**Comment by kevinold** [comment]
@frogcatcher 

You do not need to modify any of the code on the `fix-windows` branch.

Follow these steps to use the `fix-windows` branch

1. `git checkout fix-windows` 
2. `yarn install`
3. `yarn dev`

**Comment by kevinold** [comment]
> I have downgraded, now on v12.18.0
> 
> Went through all the steps again but still getting the same error.

@ahoadshieldpay Reclone the project into a new directory and verify in the terminal in VS Code that it is using Node 12.18 (via `node -v`)

**Comment by frogcatcher** [comment]
Thank you kevinold and everyone!   Mine is working now. :)

**Comment by kpmck** [comment]
I am experiencing the same behavior as @ahoadshieldpay where I am getting a **Failed to Compile** error on execution. Full error below.

**Node**: v12.18.0
**Steps to repro:**
- Fresh clone of repository (attempted in two separate directories)
- `git checkout fix-windows`
- `yarn install`
- `yarn dev`

**Error received**:
```
./src/svgs/undraw_personal_finance_tqcd.svg (./node_modules/@svgr/webpack/lib?-svgo,+titleProp,+ref!./src/svgs/undraw_personal_finance_tqcd.svg)
Error: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
Require stack:
- C:\del\cypress-realworld-app\node_modules\@svgr\webpack\node_modules\@babel\preset-env\lib\polyfills\corejs3\usage-plugin.js
- C:\del\cypress-realworld-app\node_modules\@svgr\webpack\node_modules\@babel\preset-env\lib\index.js
- C:\del\cypress-realworld-app\node_modules\@svgr\webpack\lib\index.js
- C:\del\cypress-realworld-app\node_modules\loader-runner\lib\loadLoader.js
- C:\del\cypress-realworld-app\node_modules\loader-runner\lib\LoaderRunner.js
- C:\del\cypress-realworld-app\node_modules\webpack\lib\NormalModule.js
- C:\del\cypress-realworld-app\node_modules\webpack\lib\NormalModuleFactory.js
- C:\del\cypress-realworld-app\node_modules\webpack\lib\Compiler.js
- C:\del\cypress-realworld-app\node_modules\webpack\lib\webpack.js
- C:\del\cypress-realworld-app\node_modules\react-scripts\config\webpack.config.js
- C:\del\cypress-realworld-app\node_modules\@cypress\instrument-cra\index.js
- internal/preload
```

**Comment by kevinold** [comment]
@kpmck Thanks for this report.  Investigating further.

cc @ahoadshieldpay

**Comment by kevinold** [comment]
@ahoadshieldpay @kpmck 

I've confirmed I'm able to reproduce this "Failed to compile" error locally and am investigating further.

**Comment by LucasL94** [comment]
Hey @kevinold . Could you try with some of the following?

A. Deleting `node_modules` and `yarn.lock` and then installing things again?

B. Running `yarn upgrade @babel/preset-env`

C. Adding `@babel/compat-data`

I think that some of those might fix the issue. Deleting the yarn.lock without knowing what the actual problem is might be a bad practice though

**Comment by kevinold** [comment]
@ahoadshieldpay @kpmck 

The fix just pushed to the `fix-windows` branch (https://github.com/cypress-io/cypress-realworld-app/pull/421/commits/2010c66ce94a115adc32d17f5ba35b4c7d0d9fd8) should fix your issue.

Simply `git pull` the latest from the `fix-windows` branch, run `yarn install` and `yarn start` should compile the application successfully.

cc @LucasL94

**Comment by ahoadshieldpay** [comment]
@kevinold Thank you for the quick fix, it's now working
